name: Auto-format

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  auto-format:
    name: Auto format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # A full checkout to help us push up possible changes from `deno fmt`
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Format code
        run: deno fmt

      - name: Check for changes
        id: git-check
        run: |
          if git status --porcelain | grep '.*'; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "style: auto-format code with deno fmt"
          git push