name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint code
        run: deno lint

      - name: Type check
        run: deno check main.ts

      - name: Run tests
        run: deno test --allow-read --allow-env

  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test build
        run: |
          deno compile \
            --allow-net \
            --allow-env \
            --allow-read=$HOME/.netrc \
            --target x86_64-unknown-linux-gnu \
            --output slack-emoji-typer-test \
            main.ts

      - name: Verify binary exists
        run: ls -la slack-emoji-typer-test
