name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Compile binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            artifact_name: slack-emoji-typer-linux
          - target: x86_64-pc-windows-msvc
            artifact_name: slack-emoji-typer-windows.exe
          - target: x86_64-apple-darwin
            artifact_name: slack-emoji-typer-macos
          - target: aarch64-apple-darwin
            artifact_name: slack-emoji-typer-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Compile for ${{ matrix.target }}
        run: |
          deno compile \
            --allow-net \
            --allow-env \
            --target ${{ matrix.target }} \
            --output ${{ matrix.artifact_name }} \
            main.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: ls -la artifacts/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
